name: stripe
version: 4.8.0
description: A simple Stripe API wrapper, that is meant to be used on the server.
homepage: https://github.com/enyo/stripe-dart
documentation: https://github.com/enyo/stripe-dart/blob/main/README.md
environment:
  sdk: ">=2.12.0 <3.0.0"
dependencies:
  crypto: ^3.0.2
  http: ^0.13.5
  json_annotation: ^4.8.0
  meta: ^1.9.0
  logging: ^1.1.1
  dio: ^5.0.1
dev_dependencies:
  json_serializable: ^6.6.1
  build_runner: ^2.3.3
  test: ^1.23.1
  mocktail: ^0.3.0
  lints: ^2.0.1
